# Generated by Django 2.1.2 on 2018-11-20 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('footer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('sec_type', models.CharField(max_length=1)),
                ('background_url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TheoryUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='TranslationUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_ru', models.CharField(max_length=64)),
                ('word_for', models.CharField(max_length=64)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Lesson')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Section'),
        ),
    ]
