# Generated by Django 2.1.2 on 2019-03-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190305_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedlesson',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
