# Generated by Django 2.1.2 on 2018-11-20 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181120_2207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TheoryUnit',
            new_name='Theory_Unit',
        ),
        migrations.RenameModel(
            old_name='TranslationUnit',
            new_name='Translation_Unit',
        ),
    ]
