# Generated by Django 2.0.9 on 2018-11-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181120_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
