# Generated by Django 2.0.9 on 2019-03-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_finishedlesson_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='key2lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('sing_form', models.TextField()),
                ('plur_form', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Language')),
            ],
        ),
        migrations.RemoveField(
            model_name='wordfor',
            name='language',
        ),
        migrations.RemoveField(
            model_name='wordfor',
            name='word_rus',
        ),
        migrations.RemoveField(
            model_name='wordrus',
            name='lessons',
        ),
        migrations.RenameField(
            model_name='phrase',
            old_name='phrase',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='tag',
        ),
        migrations.AddField(
            model_name='phrase',
            name='key',
            field=models.CharField(db_index=True, default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phrase',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phrase',
            name='text',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WordFor',
        ),
        migrations.DeleteModel(
            name='WordRus',
        ),
    ]
