# Generated by Django 2.1.2 on 2018-11-26 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_section_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='section',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Language'),
        ),
    ]
