# Generated by Django 2.1.2 on 2019-03-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190321_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='section',
            name='background_url',
        ),
    ]
