# Generated by Django 2.1.2 on 2018-12-12 18:14

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181212_2107'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lesson',
            managers=[
                ('lessons', django.db.models.manager.Manager()),
            ],
        ),
    ]
