# Generated by Django 2.2 on 2019-04-06 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190327_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='C', max_length=1)),
                ('task', models.TextField()),
                ('answer', models.CharField(max_length=32)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Lesson')),
            ],
        ),
    ]
