# Generated by Django 2.1.2 on 2018-12-19 17:10

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181212_2114'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lesson',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='language',
            name='url_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
