# Generated by Django 2.1.2 on 2019-01-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_section_url_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=32)),
                ('blank', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='translation_unit',
            name='tag',
        ),
        migrations.AddField(
            model_name='lesson',
            name='tag',
            field=models.CharField(default='none', max_length=32),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
