# Generated by Django 2.1.2 on 2019-01-27 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('main', '0010_auto_20190110_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('score', models.IntegerField(default=0)),
                ('avatar', models.TextField()),
                ('last_lang', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='finished_lesson',
            old_name='user_id',
            new_name='user',
        ),
    ]
