# Generated by Django 2.0.9 on 2019-01-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190110_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finished_lesson',
            old_name='user_id',
            new_name='user',
        ),
    ]
