# Generated by Django 2.1.2 on 2019-01-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190127_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='avatar',
            field=models.TextField(default='main/images/user.png'),
        ),
    ]
