# Generated by Django 2.1.2 on 2019-02-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190127_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='header',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='lesson',
            name='language',
            field=models.CharField(default='none', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation_unit',
            name='gen_for',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation_unit',
            name='gen_ru',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='section',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='section',
            name='language',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
