# Generated by Django 2.1.2 on 2019-02-13 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_auto_20190212_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=32)),
                ('phrase', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WordFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Language')),
            ],
        ),
        migrations.CreateModel(
            name='WordRus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='noun', max_length=5)),
                ('text', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Finished_Lesson',
            new_name='FinishedLesson',
        ),
        migrations.RenameModel(
            old_name='User_Profile',
            new_name='UserProfile',
        ),
        migrations.DeleteModel(
            name='Blanks',
        ),
        migrations.RemoveField(
            model_name='translation_unit',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='language',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Section'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='tag',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Language'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sec_type',
            field=models.CharField(default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='theory_unit',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Lesson'),
        ),
        migrations.DeleteModel(
            name='Translation_Unit',
        ),
        migrations.AddField(
            model_name='wordrus',
            name='lessons',
            field=models.ManyToManyField(to='main.Lesson'),
        ),
        migrations.AddField(
            model_name='wordfor',
            name='word_rus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.WordRus'),
        ),
    ]
